name: mimicry
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-12.4.0
  - conda-forge
  - defaults
dependencies:
  - blobfile==3.0.0
  - cuda-toolkit==12.4.0
  - pymoo==0.6.1.3
  - timm==0.4.12
  - torchaudio==2.5.1
  - wandb==0.20.1
  - pip:
      - llvmlite==0.43.0
      - numba==0.60.0
      - sewar==0.4.6
